name: haul
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.1  # For Google Sign-In
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.6
  firebase_storage: ^11.7.7
  image_picker: 1.1.2
  provider: 6.1.4
  intl: ^0.20.2
  firebase_app_check: ^0.2.1+8 
  url_launcher: ^6.1.10
  http: ^1.4.0
  flutter_dotenv: ^5.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/haul_logo.png
    - assets/images/onboarding1.jpg
    - assets/images/welcome_screen.jpg
    - assets/haul_logo_.png
    - assets/google_logo.png
    - assets/images/vendor.png
    - .env

flutter_native_splash:
  color: "#ffffff" 
  image: assets/haul_logo.png
  android: true
  ios: true
